[
    {
        "domain": ".google.com",
        "expirationDate": 1768113124.289598,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SAPISID",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "t29cHowiEwtRYtv-/AQ-k0XYQguXVVvykY"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1768113124.289614,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-3PAPISID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "t29cHowiEwtRYtv-/AQ-k0XYQguXVVvykY"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1749105125.520251,
        "hostOnly": false,
        "httpOnly": true,
        "name": "AEC",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "AZ6Zc-X2phV1n19_UZ4lEOC360wLKMu2M2bS07Ks2kZMZTMKcFmrDlygtiU"
    },
    {
        "domain": "mail.google.com",
        "hostOnly": true,
        "httpOnly": false,
        "name": "GMAIL_AT",
        "path": "/mail/u/0",
        "sameSite": null,
        "secure": true,
        "session": true,
        "storeId": null,
        "value": "AF6bupNxBgqIhkkLZYrVur-L4gFxTgCEpw"
    },
    {
        "domain": "mail.google.com",
        "expirationDate": 1736392417.681705,
        "hostOnly": true,
        "httpOnly": true,
        "name": "__Host-GMAIL_SCH_GML",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "1"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1749915158.55254,
        "hostOnly": false,
        "httpOnly": true,
        "name": "NID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "520=pAu70vB_jkW06og9-fhxvlBS2MjXf2A9eTPHfNuPmZrdFU5b_49G5tJO9Wu2wI7TxfIsa9vVHSksBQSJsW2QXeY6moW7Q_YwC_lYRJvk6EzFslNSdbrbHdyCwayESBv-b7Tl0paOvZopkyy9npUKLjERv6YSVcZHRlFknwStX4V0MboRyo3sdGUyMbJ7QZUxFEW5hv2jivxqezNR5HObJnW-XVzTRpZq7V8jZjESEzcXre89jgTE1D2yMkE9Hv3UVlMGJIMfAERqQUv-xrh9PPM5yGJPfx5Lyjh-SdUdv_apWhl3_co97Lynj2EW-QdBOkVOIMhBsAYdFPclDLo8Z0z53wOYcBgNcXOyrEImy3X-FYfkSWn31aw5SQxwS6cVeRAou409w53LL_4ulg"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1765639923.290032,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSIDTS",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "sidts-CjIB7wV3scJn5dZkZQA-zvmTUX1oFrvK0Q2XB1HVgwD8x_igmp_Lsp69MzxdR4BfRT23wRAA"
    },
    {
        "domain": "mail.google.com",
        "expirationDate": 1736392417.681597,
        "hostOnly": true,
        "httpOnly": true,
        "name": "__Host-GMAIL_SCH_GMS",
        "path": "/",
        "sameSite": "strict",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "1"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1768113124.289606,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-1PAPISID",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "t29cHowiEwtRYtv-/AQ-k0XYQguXVVvykY"
    },
    {
        "domain": "mail.google.com",
        "expirationDate": 1768663917.656452,
        "hostOnly": true,
        "httpOnly": true,
        "name": "OSID",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "g.a000rQgugVoymCHlgIK7NWS7aDXx3bW8qa9DGnEPINFtBFB4-ysjadSV08Lv3iPmWyARSPp46wACgYKAZ0SARcSFQHGX2MiAkpUzM2R-gIfWgU76q04MRoVAUF8yKrAumuXZ8LJ4K6a-Z6XeFqy0076"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1768113124.289542,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "g.a000rAgugSDA2WE3tjCuBCoG5dMZMRVLF3rMlrttGZkRQTxcDtvyUCtHM1x9JiZU_cg6E-cpTAACgYKAcgSARcSFQHGX2Mi9KvSDckr8zcg3_V-hipyNRoVAUF8yKpWuL6GX6DOUT3wJOvwNweL0076"
    },
    {
        "domain": "mail.google.com",
        "expirationDate": 1736392417.681382,
        "hostOnly": true,
        "httpOnly": true,
        "name": "__Host-GMAIL_SCH_GMN",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "1"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1768113124.289533,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSID",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "g.a000rAgugSDA2WE3tjCuBCoG5dMZMRVLF3rMlrttGZkRQTxcDtvyfB5XvWFtclPwXkAwZz_7zAACgYKAegSARcSFQHGX2Mivryyf6wOzJrS5YZyj8wYjhoVAUF8yKqQQp5RveZejB_YJUiCRXOD0076"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1765639993.212122,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSIDCC",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "AKEyXzX16IpJ6f-kzrklz7CRgP5SwvQZJhwMhKhE28KzKBstee1Dlt_T93oPnNP4GTMx0gHE2dk"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1765639993.212274,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSIDCC",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "AKEyXzVPOnlhWHhHHNFw-Tnj_5o1YIZAoHBcfFS9YTrkSYtdzRFzRaOvBAmEUMkShMmt4KE33g"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1765639923.290217,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSIDTS",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "sidts-CjIB7wV3scJn5dZkZQA-zvmTUX1oFrvK0Q2XB1HVgwD8x_igmp_Lsp69MzxdR4BfRT23wRAA"
    },
    {
        "domain": "mail.google.com",
        "expirationDate": 1768663917.656623,
        "hostOnly": true,
        "httpOnly": true,
        "name": "__Secure-OSID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "g.a000rQgugVoymCHlgIK7NWS7aDXx3bW8qa9DGnEPINFtBFB4-ysjD5zCYIQX6eD-WPwfAqrRbwACgYKAfUSARcSFQHGX2MiaeRgQyC5aTRTW_Ff8lqxyxoVAUF8yKqXLDOg0NplkQLhhlUnuStg0076"
    },
    {
        "domain": "mail.google.com",
        "expirationDate": 1734967924.534782,
        "hostOnly": true,
        "httpOnly": true,
        "name": "COMPASS",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "appsfrontendserver=CgAQhMPxugYaegAJa4lXHEO2uSSzgVey01FfWj-ZnstiyeDiEwFSGLJYplyVRU7v8dn__IrRJupDA2IgXy2DW8ZUChpQJh2QSCBfgtrIyFn5uNSpiH--Ir0dpEk1D8xjbttOarj-njWIkXuHkNwIT1PDFsnEE0ntYhPUQn56ZghUAJ4mIAEwAQ"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1768113124.289586,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SSID",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "AC0Z3U7aMsGtFIKFz"
    }
]
