[
    {
        "domain": ".google.com",
        "expirationDate": 1783308598.681081,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SAPISID",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "_KYkIbAmVGG2nQKL/ApEytYDKmhW9nppMH"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1783308598.681086,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-3PAPISID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "_KYkIbAmVGG2nQKL/ApEytYDKmhW9nppMH"
    },
    {
        "domain": "mail.google.com",
        "hostOnly": true,
        "httpOnly": false,
        "name": "GMAIL_AT",
        "path": "/mail/u/0",
        "sameSite": null,
        "secure": true,
        "session": true,
        "storeId": null,
        "value": "AF6bupOTcEEBCtRrS4NQaNQLKZTQDG5q5Q"
    },
    {
        "domain": "mail.google.com",
        "expirationDate": 1751340761.128777,
        "hostOnly": true,
        "httpOnly": true,
        "name": "__Host-GMAIL_SCH_GML",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "1"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1765523157.573991,
        "hostOnly": false,
        "httpOnly": true,
        "name": "NID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "524=B7aIgLf5OIgyVYU2YAQXnVTyAv9_GOdRXgURK9svLUDFzR1t5jBv4nl30xX3QPBXRBh6FqlFYjahN1YPccPsM9PaI_k4A3vO2Ar2HTz3OiT2BLwnCByCB1F7aLeILhsObkX-m1CaeCfjmpsKnavlA8H0aNU2pcXE8_yPx5x-caQUWu3v0EsDv5ebBLseV820XDRNVam-ouZbsszbl0f2Y_hvLx-MDwmXS4YPqD0kZIvHMzBxffiSfZBJAwyUL0yun9-EZmwnMTh8iyCR2sq9dgLPUv6HPoq_t-SRxY7IIGq0xy5-wiQQQiPr0b9j17NL0RAri0-6v3qXDYqFbKw-Olp8U6f4XHKhFgcRqKEg1otSO0ybUK-ML4Q2BAdSsfasfbx9mkG1TAyFhrZGjY4UV30GIoTGKUPhMWUH8nEUBqXcuaQ_k1jaKg"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1781247974.274363,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSIDTS",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "sidts-CjIB5H03P7U30vg34sNvcqn1nzt801r1rjO1uFODueTUX2AAYx-wC-HxWNBgNbB03dScSRAA"
    },
    {
        "domain": "mail.google.com",
        "expirationDate": 1751340761.128734,
        "hostOnly": true,
        "httpOnly": true,
        "name": "__Host-GMAIL_SCH_GMS",
        "path": "/",
        "sameSite": "strict",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "1"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1783308598.681083,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-1PAPISID",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "_KYkIbAmVGG2nQKL/ApEytYDKmhW9nppMH"
    },
    {
        "domain": "mail.google.com",
        "expirationDate": 1783308598.681029,
        "hostOnly": true,
        "httpOnly": true,
        "name": "OSID",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "g.a000xggugWyehwHbR-xzSw3HxruRL9AYLSOZYtFulbaaN6lJG7ogaAaoD4wursoQFynk0BEm_gACgYKAc0SARcSFQHGX2Mix_Duut85EIg-0w3jBAzcmRoVAUF8yKpz45Ve3vdrGzY-N5Q20ZmD0076"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1783308598.68105,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "g.a000xggugdq2Yl0YPPndVc9URpQZwA_tcLIHaqp0YusEogA0R-NvdBh57AHMpRo9rh6EbDmlIgACgYKASASARcSFQHGX2Mimc_Pl7muv1bUrwIanpZmYxoVAUF8yKpXVKz6eRPuLZeGDN2NDBWW0076"
    },
    {
        "domain": "mail.google.com",
        "hostOnly": true,
        "httpOnly": false,
        "name": "__Host-GMAIL_SCH",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": true,
        "storeId": null,
        "value": "nsl"
    },
    {
        "domain": "mail.google.com",
        "expirationDate": 1751340761.128662,
        "hostOnly": true,
        "httpOnly": true,
        "name": "__Host-GMAIL_SCH_GMN",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "1"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1783308598.681047,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSID",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "g.a000xggugdq2Yl0YPPndVc9URpQZwA_tcLIHaqp0YusEogA0R-NvIApZAA4uoJ2aR47XQtCi-QACgYKAWcSARcSFQHGX2MiKZ6Yiun9NGgsFnHoEw1hohoVAUF8yKpsmbJvcP13San9WFfQyQSn0076"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1781247975.750815,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSIDCC",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "AKEyXzWJD0GchK0CAGypB3X_4c-VeTe5nUrioKO6te3PQFpTlgbHT_uHj40XVBipZOOTqQW7hDo"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1781247975.750864,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSIDCC",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "AKEyXzViVSbE0tWwPB5WuzOXVCkUIMT77PiFUrpBsh8Am9at5RRYkEtyWP-J76yPtEeDujRcyw"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1781247974.274511,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSIDTS",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "sidts-CjIB5H03P7U30vg34sNvcqn1nzt801r1rjO1uFODueTUX2AAYx-wC-HxWNBgNbB03dScSRAA"
    },
    {
        "domain": "mail.google.com",
        "expirationDate": 1783308598.681033,
        "hostOnly": true,
        "httpOnly": true,
        "name": "__Secure-OSID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "g.a000xggugWyehwHbR-xzSw3HxruRL9AYLSOZYtFulbaaN6lJG7ogmkyIVHgG2hL0Pb2EVwAV4gACgYKAfQSARcSFQHGX2MiwCm8yyZdEJw3_5jfLJtO3hoVAUF8yKr4VHVp-14oauyk6rlYRGzl0076"
    },
    {
        "domain": "mail.google.com",
        "expirationDate": 1750575974.913837,
        "hostOnly": true,
        "httpOnly": true,
        "name": "COMPASS",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "appsfrontendserver=CgAQ9pSqwgYaeAAJa4lXySTgLb1Io8hrDUNUvgia1I5yJ4amhwLlrgI5uHpwtJiQ0xsDCTwVdc0DRopDs8w8ST7wyoc6wYzm8BIGZOxLDthc74fwhGq5CXoKbx-irhUA3ulRvcLDv9SLSMoVuO40cAZNeiVJR_Nb3Tf_QDWve-YO2CABMAE"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1783308598.681075,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SSID",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "ALMX93dae-5QzPkq-"
    }
]
